title: Sai Phani Krishna P
logo: "/profile.png?raw=true"
description: >
 Fullstack Software Engineer
  <br>
  <br>
  <a href="https://www.linkedin.com/in/saiphani1998/">LinkedIn Profile</a>
  <br>
  <a href="https://www.gihub.com/saiphani1998/">Gihub</a> 
theme: jekyll-theme-minimal
