title: Sai Phani Krishna P
logo: "/DisplayPic.jpeg?raw=true"
description: >
 Fullstack Software Engineer
  <br>
  <br>
  <a href="https://www.linkedin.com/in/saiphani1998/">LinkedIn Profile</a>
  <br>
  <p> Need your resume reviewed? or a 1:1 career guidance session? or a mock interview to prepare for product companies? Come block some time and I'm happy to help you!
    <a href="https://www.linkedin.com/in/saiphani1998/">LinkedIn Profile</a>
  </p>
  <br>
theme: jekyll-theme-minimal
