title: Sai Phani Krishna P
logo: "/DisplayPic.jpeg?raw=true"
description: >
 Fullstack Software Engineer 2 at Microsoft
  <br>
  <p> Need your resume reviewed? or a 1:1 career guidance session? or a mock interview to prepare for product companies? Come block some of my time at
    <a href="https://topmate.io/saiphani/">topmate</a> and I'm happy to help you!
  </p>
  <a href="https://www.linkedin.com/in/saiphani1998/">LinkedIn Profile</a>
  <br>
theme: jekyll-theme-minimal
